services:
  kanji-card:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./config.toml:/app/config.toml
    environment:
      - RUST_LOG=INFO
    restart: unless-stopped
    user: "1001:1001"
