name: Deploy kanji.uwuwu.net

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-vpn:
    runs-on: [self-hosted, uwuwu]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Deploy VPN
        run: |
          cd /root/uwuwu-vpn
          ./up.bash
